// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6RZ1HFtI3n5n_S38_be388IfQemAcLv8',
    appId: '1:78476605566:android:6a040294f6b1a46deac02f',
    messagingSenderId: '78476605566',
    projectId: 'whatsapp-clone-backend-87931',
    storageBucket: 'whatsapp-clone-backend-87931.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIDI5skVCMiSv-i6HOM0BZ02iMcEKApJI',
    appId: '1:78476605566:ios:ffa668e4834bf54deac02f',
    messagingSenderId: '78476605566',
    projectId: 'whatsapp-clone-backend-87931',
    storageBucket: 'whatsapp-clone-backend-87931.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCph_3j_C0fw68MGbHxNKbGYC3ilpVX2qQ',
    appId: '1:78476605566:web:e7a2272e5611755ceac02f',
    messagingSenderId: '78476605566',
    projectId: 'whatsapp-clone-backend-87931',
    authDomain: 'whatsapp-clone-backend-87931.firebaseapp.com',
    storageBucket: 'whatsapp-clone-backend-87931.appspot.com',
  );

}